var num1 = 10;
var num2 = -20;
var num3 = 300;
var num4 = -45.2;
var string1 = "hello";
var string2 = "goodbye";
var string3 = "goodnight";
var yes = "true";
var no = "false";
var none;
console.log("the num1 variable",num1);
console.log("the num2 variable",num2);
console.log("the num3 variable",num3);
console.log("the num4 variable",num4);
console.log("the string1 variable",string1);
console.log("the string2 variable",string2);
console.log("the string3 variable",string3);
console.log("the yes(boolean) variable",yes);
console.log("the no(boolean) variable",no);
console.log("the none(undefined) variable",none);
